Repository SC-ECE/UI-UX-DESIGN, pull requests merged in 2023-02, with the labels that each got.

#6 Income Tracker
  Income Tracker/Screenshot 2023-02-01 093854.jpg
  Income Tracker/readme.md
Labels: Hard, Synapse

#8 The universe
  The Universe/23.jpg
  The Universe/24.jpg
  The Universe/Screenshot 2023-02-01 200835.jpg
  The Universe/readme.md
Labels: Medium, Synapse

#7 Community engagement app UI Design
  Community app UI/Readme.md
Labels: Easy, Synapse
