Repository SC-ECE/UI-UX-DESIGN, pull requests merged in 2023-01, with the labels that each got.

#1 Music Application UI Design using figma
  Music App destop look UI Design/Final Project jpg.jpg
  Music App destop look UI Design/Readme.md
Labels: enhancement, Easy, Synapse

#2 NFT Art App UI Design
  NFT APP UI Design/Readme.md
  NFT APP UI Design/nft 4.png
Labels: Synapse

#4 Full UI-project uploaded successfully in organized way : )
  PS5-controller-UI_design/README.md
  PS5-controller-UI_design/images/Arkaprabha.png
  PS5-controller-UI_design/images/main graphics.png
Labels: Medium, Synapse

#5 Explore Exoplanet
  Exoplanet Explore app UI Design/Readme.md
Labels: Medium, Synapse
